### ISSUE TITLE
Support onKeyPress Events

### ISSUE THREAD

**Issue by jdmg94** [RivasCVA/react-native-code-editor#2]
please expose `onKeyPress` in order to take advantage of key combinations, this could be easily added in: https://github.com/RivasCVA/react-native-code-editor/blob/7da232ab2911d40d9b1bca7d5b34666137c5a529/src/CodeEditor.tsx#L195

**Comment by RivasCVA** [comment]
@jdmg94 For sure! I agree that having access to `onKeyPress` might be useful in certain situations.

I'm curious to know how you plan to take advantage of key combinations? Specially since the `CodeEditor` is an uncontrolled component.

**Comment by jdmg94** [comment]
@RivasCVA Thanks for making this feature happen! I ended up making a few adjustments to make this a _controlled_ components via `patch-package` I also had to use a separate native module in order to catch _hardware_ keyboard key combinations.
